/*-
 * #%L
 * matchmaking.server
 * %%
 * Copyright (C) 2016 - 2018 Frederik Kammel
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package com.github.vatbub.matchmaking.server

import com.github.vatbub.matchmaking.common.Request
import com.github.vatbub.matchmaking.common.Response
import com.github.vatbub.matchmaking.common.responses.BadRequestException
import com.github.vatbub.matchmaking.common.responses.InternalServerErrorException
import com.github.vatbub.matchmaking.server.handlers.GetConnectionIdHandler
import com.google.gson.Gson
import java.lang.Class.forName
import javax.servlet.http.HttpServlet
import javax.servlet.http.HttpServletRequest
import javax.servlet.http.HttpServletResponse

class ServerServlet(private val serverContext: ServerContext = ServerContext()) : HttpServlet() {
    private val gson = Gson()
    private val encoding = "UTF-8"

    init {
        resetHandlers()
    }

    /**
     * Removes all handlers from the server's [MessageDispatcher] and reinstantiates the default handlers
     */
    fun resetHandlers() {
        serverContext.messageDispatcher.removeAllHandlers()
        serverContext.messageDispatcher.registerHandler(GetConnectionIdHandler(serverContext.connectionIdProvider))
    }

    override fun doPost(request: HttpServletRequest?, response: HttpServletResponse?) {
        if (request == null)
            return
        if (response == null)
            return

        val requestBodyBuilder = StringBuilder()
        request.reader.lines().forEachOrdered { line -> requestBodyBuilder.append(line) }
        val requestBody = requestBodyBuilder.toString()

        val abstractRequest: Request = gson.fromJson<Request>(requestBody, Request::class.java)

        val requestClass = forName(abstractRequest.className)
        val concreteRequest = gson.fromJson(requestBody, requestClass) as Request

        var responseInteraction: Response?

        @Suppress("LiftReturnOrAssignment")
        try {
            responseInteraction = serverContext.messageDispatcher.dispatch(concreteRequest)
        } catch (e: IllegalArgumentException) {
            responseInteraction = BadRequestException(e.javaClass.name + ", " + e.message)
        } catch (e: Exception) {
            System.err.println("An internal server error occurred:")
            e.printStackTrace()
            responseInteraction = InternalServerErrorException(e.javaClass.name + ", " + e.message)
        }

        if (responseInteraction == null) {
            System.err.println("Error: No response generated")
            val e = IllegalStateException("No response generated by server")
            responseInteraction = InternalServerErrorException(e.javaClass.name + ", " + e.message)
        }

        val responseJson = gson.toJson(responseInteraction)
        response.contentType = "application/json"
        response.characterEncoding = encoding
        response.status = responseInteraction.httpStatusCode

        val responseBytes = responseJson.toByteArray(charset(encoding))
        response.outputStream.write(responseBytes)

        response.outputStream.flush()
        response.outputStream.close()
    }
}
