/*-
 * #%L
 * matchmaking.server
 * %%
 * Copyright (C) 2016 - 2018 Frederik Kammel
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package com.github.vatbub.matchmaking.server

import com.github.vatbub.matchmaking.common.Request
import com.github.vatbub.matchmaking.common.Response
import com.github.vatbub.matchmaking.common.responses.BadRequestException
import com.github.vatbub.matchmaking.common.responses.InternalServerErrorException
import com.github.vatbub.matchmaking.server.configuration.Configuration
import com.github.vatbub.matchmaking.server.configuration.ConfigurationManager
import com.github.vatbub.matchmaking.server.handlers.*
import com.google.gson.Gson
import java.lang.Class.forName
import java.net.Inet4Address
import java.net.Inet6Address
import java.net.InetAddress
import javax.servlet.http.HttpServlet
import javax.servlet.http.HttpServletRequest
import javax.servlet.http.HttpServletResponse

class ServerServlet(initialServerContext: ServerContext? = null) :
    HttpServlet() {

    private val gson = Gson()
    private val encoding = "UTF-8"
    private var serverContext: ServerContext

    init {
        serverContext = if (initialServerContext != null)
            initialServerContext
        else {
            ConfigurationManager.onChangeListeners.add(this::reloadConfiguration)
            ConfigurationManager.currentConfiguration.getAsServerContext()
        }
        resetHandlers()
    }

    override fun destroy() {
        super.destroy()
        ConfigurationManager.onChangeListeners.remove(this::reloadConfiguration)
    }

    @Suppress("UNUSED_PARAMETER")
    private fun reloadConfiguration(oldConfiguration: Configuration, newConfiguration: Configuration) {
        serverContext = newConfiguration.getAsServerContext()
        resetHandlers()
    }

    /**
     * Removes all handlers from the server's [MessageDispatcher] and reinstantiates the default handlers
     */
    fun resetHandlers() {
        serverContext.messageDispatcher.removeAllHandlers()
        serverContext.messageDispatcher.registerHandler(GetConnectionIdHandler(serverContext.connectionIdProvider))
        serverContext.messageDispatcher.registerHandler(JoinOrCreateRoomRequestHandler(serverContext.roomProvider))
        serverContext.messageDispatcher.registerHandler(DestroyRoomRequestHandler(serverContext.roomProvider))
        serverContext.messageDispatcher.registerHandler(DisconnectRequestHandler(serverContext.roomProvider))
        serverContext.messageDispatcher.registerHandler(GetRoomDataRequestHandler(serverContext.roomProvider))
        serverContext.messageDispatcher.registerHandler(SendDataToHostRequestHandler(serverContext.roomProvider))
        serverContext.messageDispatcher.registerHandler(StartGameRequestHandler(serverContext.roomProvider))
        serverContext.messageDispatcher.registerHandler(UpdateGameStateRequestHandler(serverContext.roomProvider))
    }

    override fun doPost(request: HttpServletRequest?, response: HttpServletResponse?) {
        if (request == null)
            return
        if (response == null)
            return

        val requestBodyBuilder = StringBuilder()
        request.reader.lines().forEachOrdered { line -> requestBodyBuilder.append(line) }
        val requestBody = requestBodyBuilder.toString()

        val abstractRequest: Request = gson.fromJson<Request>(requestBody, Request::class.java)

        val requestClass = forName(abstractRequest.className)
        val concreteRequest = gson.fromJson(requestBody, requestClass) as Request

        var responseInteraction: Response?

        @Suppress("LiftReturnOrAssignment")
        try {
            responseInteraction = serverContext.messageDispatcher.dispatch(
                concreteRequest,
                convertToIpv4(request.remoteAddr),
                convertToIpv6(request.remoteAddr)
            )
        } catch (e: IllegalArgumentException) {
            responseInteraction = BadRequestException(e.javaClass.name + ", " + e.message)
        } catch (e: Exception) {
            System.err.println("An internal server error occurred:")
            e.printStackTrace()
            responseInteraction = InternalServerErrorException(e.javaClass.name + ", " + e.message)
        }

        if (responseInteraction == null) {
            System.err.println("Error: No response generated")
            val e = IllegalStateException("No response generated by server")
            responseInteraction = InternalServerErrorException(e.javaClass.name + ", " + e.message)
        }

        val responseJson = gson.toJson(responseInteraction)
        response.contentType = "application/json"
        response.characterEncoding = encoding
        response.status = responseInteraction.httpStatusCode

        val responseBytes = responseJson.toByteArray(charset(encoding))
        response.outputStream.write(responseBytes)

        response.outputStream.flush()
        response.outputStream.close()
    }

    private fun convertToIpv4(ipAddress: String): Inet4Address? {

        val inetAddress = InetAddress.getByName(ipAddress)
        return if (inetAddress is Inet4Address)
            inetAddress
        else
            null
    }

    private fun convertToIpv6(ipAddress: String): Inet6Address? {

        val inetAddress = InetAddress.getByName(ipAddress)
        return if (inetAddress is Inet6Address)
            inetAddress
        else
            null
    }
}
